version: '3.8'


services:
  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery-service
    environment:
      - EUREKA_URI=http://192.168.0.138:8761/eureka
      - CONFIG_SERVER_URL=http://192.168.0.138:8888
    ports:
      - "8761:8761"
    networks:
      - com-roconmachine-io
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - com-roconmachine-io
  gatekeeper: 
    build:
      context: ./gatekeeper
      dockerfile: Dockerfile
    container_name: gatekeeper-service
    environment:
      - EUREKA_URI=http://192.168.0.138:8761/eureka
      - CONFIG_SERVER_URL=http://192.168.0.138:8888
      - OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI=http://192.168.0.138:9090/realms/com-microservice-io
    depends_on:
      - discovery
      - config-server
    ports:
      - "8080:8080"
    networks:
      - com-roconmachine-io
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    container_name: accounts-service
    ports:
      - 8090:8090
    environment:
      - CONFIG_SERVER_URL=http://192.168.0.138:8888
      - EUREKA_URI=http://192.168.0.138:8761/eureka
      - ACCOUNT_SERVER_MONGO_HOST=192.168.0.138
      - ACCOUNT_SERVER_MONGO_PORT:27017
      - ACCOUNT_SERVER_MONGO_DB:accounts

    depends_on:
      - config-server
      - discovery
      - mongodb
    networks:
      - com-roconmachine-io
  mongodb:
    image: mongo:5.0.6-focal
    container_name: mongodb

    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      #local dir/files: docker dir/files
      - $HOME/uzrnem/database/mongo_db:/data/db
      - $HOME/uzrnem/database/backup:/backup
    ports:
      - 27017:27017
    networks:
      - com-roconmachine-io
    restart: unless-stopped
networks:
  com-roconmachine-io:
    driver: bridge