spring:
    application:
        name: notification
    data:
        mongodb:
            host: localhost
            port: 27017
            database: notification
            authentication-database: admin
