openapi: 3.0.3
info:
  title: Notification API

  version: 0.1.9
servers:
  - url: http://localhost:8060
    description: Localhost

paths:
  /notify:
    post:
      summary: Add a new notification to dispatch
      operationId: addNotification
      requestBody:
        description: Create a notification to dispatch respective channel like email, sms, kafka
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestNotification'
          application/xml:
            schema:
              $ref: '#/components/schemas/RequestNotification'
        required: true
      responses:
        '201':
          description: Successful created
        '400':
          description: Bad request
        default:
          description: successful created

components:
  schemas:
    RequestNotification:
      type: object
      additionalProperties  : false
      required:
          - type
          - header
          - destinations
          - messageTemplate
      properties:
        type:
          type : string
          enum : ['EMAIL','SMS','KAFKA']

        header :
          type : string
          example : title of the message
        destinations:
          type: array
          items:
            type: string
        sender:
          type: string
        template :
            $ref : '#/components/schemas/messageTemplate'


    messageTemplate :
      type : object
      additionalProperties  : false
      required :
        - name
        - template
      properties :
        name :
          type : string

        template :
          type : string










