openapi: 3.0.3
info:
  title: Notification API

  version: 0.1.9
servers:
  - url: http://localhost:8060
    description: Localhost

paths:
  /notify:
    post:
      summary: Add a new notification to dispatch
      operationId: addNotification
      requestBody:
        description: Create a notification to dispatch respective channel like email, sms, kafka
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/notification'
          application/xml:
            schema:
              $ref: '#/components/schemas/notification'
        required: true
      responses:
        '201':
          description: Successful created
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/notification'
#            application/xml:
#              schema:
#                $ref: '#/components/schemas/notification'
        '400':
          description: Ban request
        default:
          description: successful created

components:
  schemas:
    notification:
      type: object
      required:
          - type
          - header
      properties:
        type:
          type : string
          enum : ['EMAIL','SMS','KAFKA']
          required: true
        header :
          type : string
          example : title of the message
        destinations:
          type: array
          items:
            type: string
        sender:
          type: string
        template :
            $ref : '#/components/schemas/messageTemplate'


    messageTemplate :
      type : object
      properties :
        id :
          type : integer
          format : int64
          example : 10
        name :
          type : string
        template :
          type : string









