spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: gatekeeper

logging:
  level:
    org:
      springframework:
        security: TRACE



