server:
  port: 8090

spring:
  data:
    mongodb:
      host: ${ACCOUNT_SERVER_MONGO_HOST:172.23.0.6}
      port: ${ACCOUNT_SERVER_MONGO_PORT:27017}
      database: ${ACCOUNT_SERVER_MONGO_DB:accounts}
      authentication-database: admin

