eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.0.138:8761/eureka}
  healthcheck :
    enabled : true
spring:
  cloud:
    config:
      override-system-properties: false
api:
  version : v01