server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: ${GIT_URL:https://github.com/roconmachine/microservices-io-config/}
                    username: ${GIT_USERNAME:roconmachine}
                    password: ${GIT_PASSWORD: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}

                    skipSslValidation: true
                    default-label: master


