server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: ${GIT_URL:https://github.com/roconmachine/microservices-io-config/}
                    username: ${GIT_USERNAME:roconmachine}
                    password: ${GIT_PASSWORD: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}

                    skipSslValidation: true
                    default-label: master


