server:
    address: 0.0.0.0
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/roconmachine/io.configs.git
#                    username: ${GIT_USERNAME:roconmachine}
#                    password: ${GIT_PASSWORD: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}

                    skipSslValidation: true
                    default-label: master


#    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