spring:
    application:
        name: discovery
    config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
#server:
#    port: 8761
#eureka:
#    client:
#        registerWithEureka: false
#        fetchRegistry: false